In [29]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('../datasets/customer-churn-model/Customer Churn Model.txt')
data.describe(include='all')

State  Account Length    Area Code     Phone Int'l Plan VMail Plan  \
count   3333     3333.000000  3333.000000      3333       3333       3333   
unique    51             NaN          NaN      3333          2          2   
top       WV             NaN          NaN  396-2187         no         no   
freq     106             NaN          NaN         1       3010       2411   
mean     NaN      101.064806   437.182418       NaN        NaN        NaN   
std      NaN       39.822106    42.371290       NaN        NaN        NaN   
min      NaN        1.000000   408.000000       NaN        NaN        NaN   
25%      NaN       74.000000   408.000000       NaN        NaN        NaN   
50%      NaN      101.000000   415.000000       NaN        NaN        NaN   
75%      NaN      127.000000   510.000000       NaN        NaN        NaN   
max      NaN      243.000000   510.000000       NaN        NaN        NaN   

        VMail Message     Day Mins    Day Calls   Day Charge  ...  \
count     3333.000000  3333.000000  3333.000000  3333.000000  ...   
unique            NaN          NaN          NaN          NaN  ...   
top               NaN          NaN          NaN          NaN  ...   
freq              NaN          NaN          NaN          NaN  ...   
mean         8.099010   179.775098   100.435644    30.562307  ...   
std         13.688365    54.467389    20.069084     9.259435  ...   
min          0.000000     0.000000     0.000000     0.000000  ...   
25%          0.000000   143.700000    87.000000    24.430000  ...   
50%          0.000000   179.400000   101.000000    30.500000  ...   
75%         20.000000   216.400000   114.000000    36.790000  ...   
max         51.000000   350.800000   165.000000    59.640000  ...   

          Eve Calls   Eve Charge   Night Mins  Night Calls  Night Charge  \
count   3333.000000  3333.000000  3333.000000  3333.000000   3333.000000   
unique          NaN          NaN          NaN          NaN           NaN   
top             NaN          NaN          NaN          NaN           NaN   
freq            NaN          NaN          NaN          NaN           NaN   
mean     100.114311    17.083540   200.872037   100.107711      9.039325   
std       19.922625     4.310668    50.573847    19.568609      2.275873   
min        0.000000     0.000000    23.200000    33.000000      1.040000   
25%       87.000000    14.160000   167.000000    87.000000      7.520000   
50%      100.000000    17.120000   201.200000   100.000000      9.050000   
75%      114.000000    20.000000   235.300000   113.000000     10.590000   
max      170.000000    30.910000   395.000000   175.000000     17.770000   

          Intl Mins   Intl Calls  Intl Charge  CustServ Calls  Churn?  
count   3333.000000  3333.000000  3333.000000     3333.000000    3333  
unique          NaN          NaN          NaN             NaN       2  
top             NaN          NaN          NaN             NaN  False.  
freq            NaN          NaN          NaN             NaN    2850  
mean      10.237294     4.479448     2.764581        1.562856     NaN  
std        2.791840     2.461214     0.753773        1.315491     NaN  
min        0.000000     0.000000     0.000000        0.000000     NaN  
25%        8.500000     3.000000     2.300000        1.000000     NaN  
50%       10.300000     4.000000     2.780000        1.000000     NaN  
75%       12.100000     6.000000     3.270000        2.000000     NaN  
max       20.000000    20.000000     5.400000        9.000000     NaN  

[11 rows x 21 columns]

## crear un subconjunto de datos

In [5]:
#tomo los nombres de todas las columnas:
all_columns = data.columns.values.tolist()
all_columns

['State',
 'Account Length',
 'Area Code',
 'Phone',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Mins',
 'Day Calls',
 'Day Charge',
 'Eve Mins',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [6]:
#hago una lista con las columnas que deseo trabajar
columnas_deseadas = ['State', 'Phone', 'Day Mins', 'Eve Mins']

In [10]:
#armo una lista con las columnas NO deseadas, aplicando un for...
columnas_no_deseadas = [x for x in all_columns if x not in columnas_deseadas]
columnas_no_deseadas

['Account Length',
 'Area Code',
 "Int'l Plan",
 'VMail Plan',
 'VMail Message',
 'Day Calls',
 'Day Charge',
 'Eve Calls',
 'Eve Charge',
 'Night Mins',
 'Night Calls',
 'Night Charge',
 'Intl Mins',
 'Intl Calls',
 'Intl Charge',
 'CustServ Calls',
 'Churn?']

In [11]:
columnas_deseadas

['State', 'Phone', 'Day Mins', 'Eve Mins']

In [15]:
#otra forma, sin el bucle
res = set(columnas_deseadas)-set(columnas_no_deseadas)
list(res)

['State', 'Eve Mins', 'Phone', 'Day Mins']

In [27]:
data.iloc[5:11,0:3]

State  Account Length  Area Code
5     AL             118        510
6     MA             121        510
7     MO             147        415
8     LA             117        408
9     WV             141        415
10    IN              65        415

In [28]:
data.iloc[[5,10,15,20,25], 3:6]

Phone Int'l Plan VMail Plan
5   391-8027        yes         no
10  329-6603         no         no
15  351-7269         no         no
20  396-5800         no         no
25  331-3698         no         no

## generar nros aleatorios

In [31]:
#generar entre 0 y 1
np.random.random(10)

array([0.77076766, 0.57931615, 0.594458  , 0.04879572, 0.31080907,
       0.69879298, 0.91231881, 0.53196615, 0.90347852, 0.08152411])

In [33]:
np.random.randint(1,10,5)

array([8, 8, 7, 2, 8])

In [40]:
#generar un rango de valores y desordenarlo
a = np.arange(100)
np.random.shuffle(a)
a

array([98, 25, 40, 31,  1, 68, 97, 33, 71, 47, 14, 76, 73, 58, 64,  0, 55,
       93, 85,  6, 45, 84, 29, 42, 26, 35, 62, 18, 65, 95, 61, 75, 72, 89,
        7, 20, 23, 81,  8, 10, 17, 48, 37, 16,  5,  3, 38, 57, 34, 87, 63,
       21, 56, 50, 74, 13, 24, 69, 99, 60, 44, 15, 78, 91, 22, 11, 96, 77,
       92, 54, 30, 94, 43, 41, 86,  2, 80, 32, 90, 53, 59, 51, 12, 49, 19,
       36, 67, 27, 79, 82, 39, 52, 83, 46, 88, 28,  4, 66, 70,  9])

In [41]:
#y puedo seleccionar de forma aleatoria una equis cantidad de filas
data.iloc[a,1:2]

Account Length
98             120
25             174
40              98
31              75
1              107
..             ...
28              20
4               75
66              43
70             138
9              141

[100 rows x 1 columns]

In [45]:
#con numpy se puede seleccionar un elemento aleatorio
np.random.choice(columnas_no_deseadas)

'Eve Charge'

In [46]:
np.random.seed(2018)
for i in range(5):
    print(np.random.random())

0.8823493117539459
0.10432773786047767
0.9070093335163405
0.3063988986063515
0.446408872427422
